# This is used to build the TechDochs for this component and is referenced here: https://github.com/benwilcock/backstage-catalogs/blob/main/system-polyglot-demo.yml
site_name: 'springboot-maven'
site_description: 'A Spring Boot sample built using Maven'
site_author: user:ben.wilcock

nav:
  - About: 'index.md'